#!/bin/bash
#SBATCH -J adcpost           # Job name
#SBATCH -o post.out       # Name of stdout output file
#SBATCH -e post.err       # Name of stderr error file
#SBATCH -p development        # Queue (partition) name
#SBATCH -N 1                # Total # of nodes
#SBATCH -n 1              # Total # of mpi tasks
#SBATCH -t 02:00:00          # Run time (hh:mm:ss)
#SBATCH --mail-type=all      # Send email at begin and end of job
#SBATCH --mail-user=namo26june@gmail.com
#SBATCH -A ADCIRC

rename 'DG' 'DG.old' PE*/DG.6*
./adcpost < out.prep

