#!/bin/bash
#SBATCH -J plot           # Job name
#SBATCH -o plot.out       # Name of stdout output file
#SBATCH -e plot.err       # Name of stderr error file
#SBATCH -p development        # Queue (partition) name
#SBATCH -N 1                # Total # of nodes
#SBATCH -n 64              # Total # of mpi tasks
#SBATCH -t 01:00:00          # Run time (hh:mm:ss)
#SBATCH --mail-type=all      # Send email at begin and end of job
#SBATCH --mail-user=namo26june@gmail.com
#SBATCH -A ADCIRC

ibrun ./runFG51par -I shin.inp

